<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KARIM-MSI" failures="1" tests="2" name="Error Validation Test" time="53.962" errors="0" timestamp="2023-09-13T17:00:54 BST">
  <testcase classname="testcases.FillForm_Validation" name="FillForm_NegativeTest" time="16.603">
    <failure type="java.lang.AssertionError" message="expected [Please enter your name1] but found [Please enter your name]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your name1] but found [Please enter your name]
at testcases.FillForm_Validation.FillForm_NegativeTest(FillForm_Validation.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- FillForm_NegativeTest -->
  <testcase classname="testcases.FillForm_Validation" name="FillForm_PositiveTest" time="25.616"/>
</testsuite> <!-- Error Validation Test -->
